In [81]:
import numpy as np

def etas(z):
    if isinstance(z, float):
        if z < -0.5:
            v = sqrt(-z)
            return cos(v), sin(v)/v
        elif z > 0.5:
            v = sqrt(z)
            return cosh(v), sinh(v)/v
        else:
            return (
                1/3628800*z^5 + 1/40320*z^4 + 1/720*z^3 + 1/24*z^2 + 1/2*z + 1,
                1/39916800*z^5 + 1/362880*z^4 + 1/5040*z^3 + 1/120*z^2 + 1/6*z + 1
            )
    else:
        assert len(z.shape) == 1
        r = np.ndarray((z.shape[0], 2))
        low = np.where(z <= -0.5)
        mid = np.where(np.logical_and(-0.5 < z, z < 0.5))
        high = np.where(z >= 0.5)
        sz = np.sqrt(np.abs(z))
        r[low, 0] = np.cos(sz[low])
        r[low, 1] = np.sin(sz[low])/sz[low]
        r[high, 0] = np.cosh(sz[high])
        r[high, 1] = np.sinh(sz[high])/sz[high]
        zm = z[mid]
        r[mid, 0] = zm**5/3628800 + zm**4/40320 + zm**3/720 + zm**2/24 + zm/2 + 1,
        r[mid, 1] = zm**5/39916800 + zm**4/362880 + zm**3/5040 + zm**2/120 + zm/6 + 1,
        return r

class Basis:
    def __init__(self, Z):
        Z = float(Z)
        self.Z = Z
        s = Z/2
        freqs = [(s, s)]
        for i in range(1, 5):
            AA = s + i*5
            BB = Z - AA
            freqs.append((AA, BB))
            freqs.append((BB, AA))
        self.freqs = np.array(freqs)

    def __call__(self, x, y):
        x = float(x)
        y = float(y)
        ex = etas(self.freqs[:, 0]*x*x)
        ey = etas(self.freqs[:, 1]*y*y)
        r = np.ndarray((len(self.freqs), 4))
        r[:, 0] = ex[:, 0] * ey[:, 0]
        r[:, 1] = ex[:, 0] * ey[:, 1]
        r[:, 2] = ex[:, 1] * ey[:, 0]
        r[:, 3] = ex[:, 1] * ey[:, 1]
        return r
    
b = Basis(5)
etas(np.array([-2, -0.1, 0.1, 2]))

array([[0.15594369, 0.698456  ],
       [0.95041528, 0.98341647],
       [1.05041806, 1.0167502 ],
       [2.17818356, 1.36829887]])

In [82]:
b.freqs

array([[  2.5,   2.5],
       [  7.5,  -2.5],
       [ -2.5,   7.5],
       [ 12.5,  -7.5],
       [ -7.5,  12.5],
       [ 17.5, -12.5],
       [-12.5,  17.5],
       [ 22.5, -17.5],
       [-17.5,  22.5]])

In [83]:
b(0, 0.3)

array([[1.11462526, 1.03792414, 1.11462526, 1.03792414],
       [0.88959362, 0.96291962, 0.88959362, 0.96291962],
       [1.35691671, 1.11635847, 1.35691671, 1.11635847],
       [0.68106234, 0.89123642, 0.68106234, 0.89123642],
       [1.61725214, 1.19833384, 1.61725214, 1.19833384],
       [0.48829607, 0.82276874, 0.48829607, 0.82276874],
       [1.89644106, 1.28396427, 1.89644106, 1.28396427],
       [0.31058299, 0.7574134 , 0.31058299, 0.7574134 ],
       [2.19531895, 1.37336665, 2.19531895, 1.37336665]])

In [24]:
taylor(cosh(sqrt(x)), x, 0, 5)

1/3628800*x^5 + 1/40320*x^4 + 1/720*x^3 + 1/24*x^2 + 1/2*x + 1

In [20]:
n = 1
cx = [var(f'c_{i}x') for i in range(n)]
cy = [var(f'c_{i}y') for i in range(n)]

A = []
Ax = [var(f'A_{i}x') for i in range(n)]
Ay = [var(f'A_{i}y') for i in range(n)]

var('E, Vbar')
Z = Vbar - E

f(x, y) = sum(cx[i]*exp(Ax[i]*x + sqrt(Z - Ax[i]**2)*y) for i in range(n)) + sum(cy[i]*exp(Ay[i]*y + sqrt(Z - Ay[i]**2)*x) for i in range(n))
f

(x, y) |--> c_0x*e^(A_0x*x + sqrt(-A_0x^2 - E + Vbar)*y) + c_0y*e^(A_0y*y + sqrt(-A_0y^2 - E + Vbar)*x)

In [21]:
(-(diff(f, x, x) + diff(f, y, y)) + Z * f).simplify_full()

(x, y) |--> 0

In [30]:
diff(f, y)(x, 0)

A_0y*c_0y*e^(sqrt(-A_0y^2 - E + Vbar)*x) + sqrt(-A_0x^2 - E + Vbar)*c_0x*e^(A_0x*x)

In [31]:
var('psi')
psi_k = [var(f'psi_{i}') for i in range(5)]



[psi_0, psi_1, psi_2, psi_3, psi_4]

In [42]:
var('A, B, x')
v = solve(integrate((cos(x)-1)*(cos(B*x) - 1), x, 0, pi) == 0, (B,), solution_dict=True)
v

[{B: -1/18*(-I*sqrt(3) + 1)*(4*sin(pi*B)^2/pi^2 + 3)/(-1/6*sin(pi*B)/pi + 8/27*sin(pi*B)^3/pi^3 + 1/6*sqrt(-4/3*pi^4 - 13/3*pi^2*sin(pi*B)^2 - 32/3*sin(pi*B)^4)/pi^2)^(1/3) - 1/2*(I*sqrt(3) + 1)*(-1/6*sin(pi*B)/pi + 8/27*sin(pi*B)^3/pi^3 + 1/6*sqrt(-4/3*pi^4 - 13/3*pi^2*sin(pi*B)^2 - 32/3*sin(pi*B)^4)/pi^2)^(1/3) + 2/3*sin(pi*B)/pi},
 {B: -1/18*(I*sqrt(3) + 1)*(4*sin(pi*B)^2/pi^2 + 3)/(-1/6*sin(pi*B)/pi + 8/27*sin(pi*B)^3/pi^3 + 1/6*sqrt(-4/3*pi^4 - 13/3*pi^2*sin(pi*B)^2 - 32/3*sin(pi*B)^4)/pi^2)^(1/3) - 1/2*(-I*sqrt(3) + 1)*(-1/6*sin(pi*B)/pi + 8/27*sin(pi*B)^3/pi^3 + 1/6*sqrt(-4/3*pi^4 - 13/3*pi^2*sin(pi*B)^2 - 32/3*sin(pi*B)^4)/pi^2)^(1/3) + 2/3*sin(pi*B)/pi},
 {B: 1/9*(4*sin(pi*B)^2/pi^2 + 3)/(-1/6*sin(pi*B)/pi + 8/27*sin(pi*B)^3/pi^3 + 1/6*sqrt(-4/3*pi^4 - 13/3*pi^2*sin(pi*B)^2 - 32/3*sin(pi*B)^4)/pi^2)^(1/3) + (-1/6*sin(pi*B)/pi + 8/27*sin(pi*B)^3/pi^3 + 1/6*sqrt(-4/3*pi^4 - 13/3*pi^2*sin(pi*B)^2 - 32/3*sin(pi*B)^4)/pi^2)^(1/3) + 2/3*sin(pi*B)/pi}]

In [60]:
def dot(u, v):
    return integrate(u*v, x, 0, 1)

fs = [cosh(pi*x)-1]
fs[-1] = (fs[-1]/sqrt(dot(fs[-1], fs[-1]))).simplify_full()

for i in range(1, 3):
    c = cos(x*i*pi)
    n = c
    for f in fs:
        n -= dot(f, c)*f
    print(n)
    n = (n / sqrt(dot(n, n))).simplify_full()
    fs.append(n)

sqrt(2)*(sqrt(2)*cosh(pi*x)*e^pi - sqrt(2)*e^pi)*(e^(2*pi) - 1)/(12*pi*e^(2*pi) - 16*e^(2*pi)*sinh(pi) + e^(4*pi) - 1) + cos(pi*x)
-2/5*sqrt(2)*(sqrt(2)*cosh(pi*x)*e^pi - sqrt(2)*e^pi)*(e^(2*pi) - 1)/(12*pi*e^(2*pi) - 16*e^(2*pi)*sinh(pi) + e^(4*pi) - 1) - 1/5*(12*pi^2*e^(2*pi) - 16*pi*e^(2*pi)*sinh(pi) + pi*(e^(4*pi) - 1))*((12*sqrt(2)*pi*e^(2*pi) - 16*sqrt(2)*e^(2*pi)*sinh(pi) + sqrt(2)*e^(4*pi) - sqrt(2))*cos(pi*x) - 2*(sqrt(2)*e^pi - sqrt(2)*e^(3*pi))*cosh(pi*x) + 2*sqrt(2)*e^pi - 2*sqrt(2)*e^(3*pi))*(sqrt(2)*e^(4*pi) - 2*sqrt(2)*e^(2*pi) + sqrt(2))/(pi*(12*pi^2*e^(2*pi) - 16*pi*e^(2*pi)*sinh(pi) + pi*(e^(4*pi) - 1) - e^(4*pi) + 2*e^(2*pi) - 1)*(12*pi*e^(2*pi) - 16*e^(2*pi)*sinh(pi) + e^(4*pi) - 1)^2) + cos(2*pi*x)


In [ ]:
sum(plot(f, (x, 0, 1), color=hue(golden_ratio*i)) for i, f in enumerate(fs))